### ISSUE TITLE
"Select Multiple" shouldn't show up when there are no records.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-pro/bullet_train-action_models#48]
<img width="1204" alt="Screenshot 2023-03-01 at 9 01 11 PM" src="https://user-images.githubusercontent.com/217218/222335624-685a29bf-4f3d-4376-88b2-a9ba9fd90c9a.png">

**Comment by gazayas** [comment]
Closing this one because it has been implemented properly.

![Screenshot from 2023-09-30 10-24-30](https://github.com/bullet-train-pro/bullet_train-action_models/assets/10546292/4fff5073-67b3-4f18-aea9-451e868b4efc)

![Screenshot from 2023-09-30 10-24-49](https://github.com/bullet-train-pro/bullet_train-action_models/assets/10546292/6a606c12-d01b-4cbf-b7ac-6381bfffdae0)

![Screenshot from 2023-09-30 10-25-02](https://github.com/bullet-train-pro/bullet_train-action_models/assets/10546292/163b6c07-fc9d-49f8-a7b0-9679a5e1e263)
